### ISSUE TITLE
Pending issues

### ISSUE THREAD

**Issue by RMattHutchison** [Brainhack-Proceedings-2015/Kan-AMX-ENIGMA-Wrapper-Scripts#2]
Kan et al., have developed wrapper scripts to facilitate the use of ENIGMA protocols. This is an often-ignored area when implementing large data sharing initiatives and an area that should be developed. I suspect that the number of users that have avoided result sharing or even attempted and became frustrated with the process is quite higher than most would like to admit. I only have several minor comments for the authors to address.
1.  Include a table of the 3 main scripts, what they do, and approximate time for completion for a single subject on a standard workstation. i.e Script 1: Freesurfer surface generation, 12hrs.
2.  Flip the scale in the table. It is more intuitive to have 1 as easiest and 10 as hardest.
3.  Typo in the table, “eaies” should be “easiest”.
4.  Typo in “To address this, we created a 3 easy-to-use wrapper scripts that”. Remove “a”.
5.  Authors state that “we tested each of them on 6 users who…”, but the table has 7 users.
6.  Fill in the sections: Availability of Supporting Data, Competing interests, Author's contributions, Acknowledgements
7.  For cited references use Author et al… Will eliminate an entire page.

**Comment by npnl** [comment]
We thank the reviewer for these helpful comments and feedback. We have responded to them below. To note, we have made these changes on our own repository since we didn't have permissions to update on Brainhack Proceedings (and our latex version produced some strange formatting issues that we're currently working on), but for now you can find the changes here: https://github.com/npnl/ENIGMA-Wrapper-Scripts/blob/master/ENIGMA-Abstract/20160325-brainhack-abstract-formatted-.pdf

Kan et al., have developed wrapper scripts to facilitate the use of ENIGMA protocols. This is an often-ignored area when implementing large data sharing initiatives and an area that should be developed. I suspect that the number of users that have avoided result sharing or even attempted and became frustrated with the process is quite higher than most would like to admit. I only have several minor comments for the authors to address.

(1) Include a table of the 3 main scripts, what they do, and approximate time for completion for a single subject on a standard workstation (i.e. Script 1: Freesurfer surface generation, 12hrs).

This is a great suggestion; we have included this as Table 1, and moved the current table to Table 2. We have also included this in the beginning of our readme document.
1. Flip the scale in the table. It is more intuitive to have 1 as easiest and 10 as hardest.

We have flipped the scale in the table as suggested.
1. Typo in the table, “eaies” should be “easiest”.

Thanks for catching this error. We have fixed this. 
1. Typo in “To address this, we created a 3 easy-to-use wrapper scripts that”. Remove “a”.

Thanks for catching this error. We have fixed this. 
1. Authors state that “we tested each of them on 6 users who…”, but the table has 7 users.

Thanks for catching this error. We have updated this to 7.
1. Fill in the sections: Availability of Supporting Data, Competing interests, Author's contributions, Acknowledgements

Thanks for pointing this out. We have updated these sections as follows:

Availability of Supporting Data: Can provide a test dataset on request; if interested, please email npnl@usc.edu.

Competing interests: None

Author's contributions: Eric Kan, Julia Anglin, and Sook-Lei Liew wrote the wrapper scripts. Neda Jahanshad and Paul Thompson developed the original ENIGMA protocols and provide guidance/support for ENIGMA working groups. Michael Borich, Julia Anglin, and Sook-Lei Liew tested and edited the wrapper scripts. All authors contributed to the creation of the manuscript.

Acknowledgements: We thank all of our testers.

**Comment by RMattHutchison** [comment]
Everything looks great.
Nice work.
On Mar 25, 2016, at 10:21 PM, npnl <notifications@github.com<mailto:notifications@github.com>> wrote:

We thank the reviewer for these helpful comments and feedback. We have responded to them below. To note, we have made these changes on our own repository since we didn't have permissions to update on Brainhack Proceedings (and our latex version produced some strange formatting issues that we're currently working on), but for now you can find the changes here: https://github.com/npnl/ENIGMA-Wrapper-Scripts/blob/master/ENIGMA-Abstract/20160325-brainhack-abstract-formatted-.pdfhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_npnl_ENIGMA-2DWrapper-2DScripts_blob_master_ENIGMA-2DAbstract_20160325-2Dbrainhack-2Dabstract-2Dformatted-2D.pdf&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=69k3NvyREONVTQ_JClHXawrI1ACZamc6MwjthyqjeHg&m=rbUZQT16ZKtWoQA8wasXUKfL3gWWD3RZiVFfDUMLlk4&s=Lux9ibd2zk8SOa3RmGl5UYJbTcrFcvSWXND47vxcEds&e=

Kan et al., have developed wrapper scripts to facilitate the use of ENIGMA protocols. This is an often-ignored area when implementing large data sharing initiatives and an area that should be developed. I suspect that the number of users that have avoided result sharing or even attempted and became frustrated with the process is quite higher than most would like to admit. I only have several minor comments for the authors to address.

(1) Include a table of the 3 main scripts, what they do, and approximate time for completion for a single subject on a standard workstation (i.e. Script 1: Freesurfer surface generation, 12hrs).

This is a great suggestion; we have included this as Table 1, and moved the current table to Table 2. We have also included this in the beginning of our readme document.
1.  Flip the scale in the table. It is more intuitive to have 1 as easiest and 10 as hardest.

We have flipped the scale in the table as suggested.
1.  Typo in the table, “eaies” should be “easiest”.

Thanks for catching this error. We have fixed this.
1.  Typo in “To address this, we created a 3 easy-to-use wrapper scripts that”. Remove “a”.

Thanks for catching this error. We have fixed this.
1.  Authors state that “we tested each of them on 6 users who…”, but the table has 7 users.

Thanks for catching this error. We have updated this to 7.
1.  Fill in the sections: Availability of Supporting Data, Competing interests, Author's contributions, Acknowledgements

Thanks for pointing this out. We have updated these sections as follows:

Availability of Supporting Data: Can provide a test dataset on request; if interested, please email npnl@usc.edumailto:npnl@usc.edu.

Competing interests: None

Author's contributions: Eric Kan, Julia Anglin, and Sook-Lei Liew wrote the wrapper scripts. Neda Jahanshad and Paul Thompson developed the original ENIGMA protocols and provide guidance/support for ENIGMA working groups. Michael Borich, Julia Anglin, and Sook-Lei Liew tested and edited the wrapper scripts. All authors contributed to the creation of the manuscript.

Acknowledgements: We thank all of our testers.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Brainhack-2DProceedings-2D2015_Kan-2DAMX-2DENIGMA-2DWrapper-2DScripts_issues_2-23issuecomment-2D201675435&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=69k3NvyREONVTQ_JClHXawrI1ACZamc6MwjthyqjeHg&m=rbUZQT16ZKtWoQA8wasXUKfL3gWWD3RZiVFfDUMLlk4&s=VeRtZUVfRnzPVuPqBlXuiQtOggqrG_6QI2Nb93IB0N0&e=

## 

R. Matthew Hutchison, PhD.
Sir Fredrick Banting Postdoctoral Fellow
Harvard University
Center for Brain Science
https://sites.google.com/site/RMatthewHutchison

**Comment by nicholsn** [comment]
@ccraddock this looks good to close.
