### ISSUE TITLE
Review: Great Contribution

### ISSUE THREAD

**Issue by dbkeator** [Brainhack-Proceedings-2015/Kan-AMX-ENIGMA-Wrapper-Scripts#3]
This project aims at evaluating the ease of use of the ENIGMA protocols for structural analysis and reducing the complexity of executing the analysis for novice users.  Decreasing barriers for wider adoption of analysis pipelines is an important contribution for re-use and standardization of protocols.  The abstract is well written and the time x user level empirical results are interesting.  

(1) Minor typo in this sentence: "To address this we created a 3 easy-to-use wrapper scripts"
(2) Regarding the ~2hr time for the expert user to implement the pipeline on a different environment, what specifically was the difficulty?  Was this an environment not supported by Freesurfer and thus required compilation and/or adding libraries?  Why did the data need reorganization?  I would assume the data organization wouldn't change even though one is running the scripts on a different platform.
(3) Bash is a standard shell but there are those who use CSH or TCSH.  I'm wondering why you chose to write the scripts in Bash instead of Python, for example?

**Comment by npnl** [comment]
Thanks for the very helpful comments! We have responded to them below. To note, we have made these changes on our own repository since we didn't have permissions to update on Brainhack Proceedings (and our latex version produced some strange formatting issues that we're currently working on), but for now you can find the changes here: https://github.com/npnl/ENIGMA-Wrapper-Scripts/blob/master/ENIGMA-Abstract/20160325-brainhack-abstract-formatted-.pdf 

(1) Minor typo in this sentence: "To address this we created a 3 easy-to-use wrapper scripts"

We thank the reviewer for pointing this out – this typo has been fixed.

(2) Regarding the ~2hr time for the expert user to implement the pipeline on a different environment, what specifically was the difficulty? Was this an environment not supported by Freesurfer and thus required compilation and/or adding libraries? Why did the data need reorganization? I would assume the data organization wouldn't change even though one is running the scripts on a different platform.

This is a great question, and one that we have updated the following information from this: 

Finally, the expert users who had to reorganize the environment took 2-3 hours, but about 10 minutes was script implementation and the remainder of the time was troubleshooting Freesurfer errors.

to this:

Finally, the expert users who implemented the scripts on their own environment found the most time-consuming steps to be installing and troubleshooting Freesurfer (e.g., install errors; troubleshooting a conflict between the preset Freesurfer subjects directory and the output directory required by the scripts) and reorganizing data into a format for the scripts (e.g., putting the data into an organized format with main_folder/subject_folder/subject.nii.gz). Once these steps were complete, each expert user reported about 10 minutes for script implementation.

(3) Bash is a standard shell but there are those who use CSH or TCSH. I'm wondering why you chose to write the scripts in Bash instead of Python, for example?

This is a great suggestion and one that we plan to implement in the future. Unfortunately, we are less familiar with python (something we are working on now!) and so were only able to complete this successfully in bash.

**Comment by nicholsn** [comment]
@dbkeator do these comments address your suggestions?

**Comment by dbkeator** [comment]
@nicholsn  Yes, they did.

**Comment by nicholsn** [comment]
Thanks! @ccraddock can you close?
